### ISSUE TITLE
组件添加border

### ISSUE THREAD

**Issue by iboying** [iwgang/CountdownView#10]
可以给是时间加自定义的背景吗？比如这样的border:
![image](https://cloud.githubusercontent.com/assets/10523771/16411869/dd7674b6-3d5b-11e6-935a-9d6b5bd375b2.png)

**Comment by iwgang** [comment]
谢谢建议，后面会考虑

**Comment by iboying** [comment]
期待，已watch

**Comment by iwgang** [comment]
![device-2016-06-30-172318](https://cloud.githubusercontent.com/assets/3657121/16484016/a41dc540-3ee9-11e6-9936-652950d0ae08.png)

已经完成，放出Gradle
