### ISSUE TITLE
countUp on orientation change

### ISSUE THREAD

**Issue by yudikarma** [iwgang/CountdownView#121]
hi thank before to awesome libraries
i want to make app to count down but i will to count up when phone orientation change .
like hourglass timed. can i do it with countdownVIew ? i not find that in documentation
thanks for help

**Comment by yudikarma** [comment]
i mean how to do if i want to count Up

**Comment by iwgang** [comment]
```countdownView.updateShow(time...)``` ?

**Comment by yudikarma** [comment]
yupss. finaly i found that. thanks @iwgang  for awesome libraries. can i use this librarie for commercial project ? where i put your lincense. thanks

**Comment by iwgang** [comment]
@yudikarma   ok
