### ISSUE TITLE
你好请教几个问题

### ISSUE THREAD

**Issue by liuxuesong001** [iwgang/CountdownView#122]
1.控件默认的值是00：00：00 比如我想 默认给个倒计时1分钟 然后点击start开始倒计时？如何更改？
2.是否不再维护？
3.是否添加service服务，退出程序重新启动，还可以继续倒计时？

**Comment by iwgang** [comment]
1. 修改时间继续 start 就好了
2.  会继续维护，只不过近期忙都在其它事情，精力有限，只会处理一些解答形的 is
3. 倒计时自己维护好，把 CountdownView 当作是一个 TextView 就好了，然后调用  ```updateShow()``` 去更新
