### ISSUE TITLE
正确设置时间，但是调用方法getDay,getHour获取天，小时数 都返回0

### ISSUE THREAD

**Issue by wangdroid** [iwgang/CountdownView#123]

**Comment by iwgang** [comment]
能否提供下代码

**Comment by wangdroid** [comment]
countdownView = findViewById(R.id.countDownView);
countdownView.start(1000 * 60 * 60 * 24 * 2);
Toast.makeText(MyTestAct.this, "获取天数:" + countdownView.getDay(), Toast.LENGTH_LONG).show();
界面倒计时显示正常，toast打印天数为0

**Comment by iwgang** [comment]
这里想立即拿没有值，因为还没有进行绘制刷新流程去赋值

以前多数有可能用到这些 getXxx 方法场景会在 setOnCountdownIntervalListener 中

如果你需要给值后立即显示，还是建议自己转换来显示
