### ISSUE TITLE
RecyclerView列表，倒计时结束问题

### ISSUE THREAD

**Issue by shenjiabing** [iwgang/CountdownView#127]
![QQ图片20190326153119](https://user-images.githubusercontent.com/45984638/54978782-41fcd980-4fdc-11e9-92ef-6d6774d83ef3.png)
RecyclerView列表做倒计时效果，上下滑动后，有的item倒计时结束没有走onEnd这个方法，想做成倒计时结束，刷新item

**Comment by jackyglony** [comment]
楼上的，这个问题有解决吗？

**Comment by shenjiabing** [comment]
还是没找到解决方案，你也遇到这个问题了吗？

**Comment by zzzsssbo** [comment]
因为列表滑动导致item被复用了

**Comment by jzm369** [comment]
@zhangshaobo87 我遇到相同问题，请问如何解决呢

**Comment by shenjiabing** [comment]
这样就可以了
 /**
     * 列表倒计时
     */
    private void startTime() {
        new Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                mActivity.runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        if (mTimeDownBeanList==null){
                            return;
                        }
                        for (int i = 0; i < mTimeDownBeanList.size(); i++) {
                            long useTime = mTimeDownBeanList.get(i).getUseTime();
                            if (useTime > 1000) {
                                useTime -= 1000;
                                mTimeDownBeanList.get(i).setUseTime(useTime);
                                if (useTime <= 1000 && mTimeDownBeanList.get(i).isTimeFlag()) {
                                    mTimeDownBeanList.get(i).setTimeFlag(false);
                                    CountDownDemoAdapter.this.notifyItemChanged(i);
                                }else {
                                    mTimeDownBeanList.get(i).setTimeFlag(true);
                                    CountDownDemoAdapter.this.notifyItemChanged(i);
                                }

                            }

                        }

                    }
                });


            }
        }, 0, 1000);
    }



    @Override
    protected void convert(CountDownDemoHolder helper, TimeDownBean item) {
        CountdownView mCountdownView=helper.getView(R.id.mCountdownView);
        TimeDownBean timeDownBean = item;
        if (item.getUseTime()>1000){
            helper.timeTv.setVisibility(View.VISIBLE);
//            long useTime = timeDownBean.getUseTime();
//            useTime = useTime / 1000;
//            setTimeShow(useTime, helper);

            mCountdownView.setVisibility(View.VISIBLE);
            mCountdownView.start(timeDownBean.getUseTime());
        }else {
            helper.timeTv.setVisibility(View.GONE);
            mCountdownView.setVisibility(View.INVISIBLE);
        }

        helper.setText(R.id.content_tv,item.isTimeFlag()+"--"+item.getContent());
    }

**Comment by iwgang** [comment]
列表要自己维护倒计时，CountdownView 只能作为显示，因为会被复用，没办法做状态
