### ISSUE TITLE
setConvertDaysToHours(true)

### ISSUE THREAD

**Issue by huangzhuhua666** [iwgang/CountdownView#130]
`DynamicConfig config = new DynamicConfig.Builder()
                                .setConvertDaysToHours(true)
                                .build();`
使用背景的时候，设置把天数转换成小时。控件会显示不全，往右移，秒数被遮挡了一半。怎么解决？

**Comment by ZhangWenkaidyy** [comment]
设置左右padding 可以解决

**Comment by fendounan** [comment]
正解！

> 设置左右padding 可以解决
