### ISSUE TITLE
time background not showing

### ISSUE THREAD

**Issue by hassanrana** [iwgang/CountdownView#134]
Hello,can anyone help me why the time background is not showing?i have set the time background size.

<cn.iwgang.countdownview.CountdownView
                    android:id="@+id/countdownView"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:isShowDay="true"
                    app:isShowHour="true"
                    app:isShowMinute="true"
                    app:isShowSecond="true"
                    app:timeTextColor="#fff"
                    app:timeTextSize="22sp"
                    app:isTimeTextBold="true"
                    app:suffixGravity="bottom"
                    app:suffixTextColor="#fff"
                    app:suffixTextSize="12sp"
                    app:suffixHour="Hours"
                    app:suffixMinute="Min"
                    app:suffixSecond="Sec"
                    app:suffixDay="Days"
                    android:layout_marginTop="8dp"
                    app:timeBgBorderSize="20dp"
                    app:timeBgSize="300dp"
                    app:timeBgColor="#000"
                    app:isShowTimeBgBorder="true" />

**Comment by iwgang** [comment]
```
isHideTimeBackground="false"
```
