### ISSUE TITLE
出现负时间

### ISSUE THREAD

**Issue by javakam** [iwgang/CountdownView#14]
出现负时间的问题。。。出现负时间UI错乱不好看。。

**Comment by iwgang** [comment]
什么情况下？

**Comment by sliverloong** [comment]
我这里也出现了负时间，调用updateShow（3922689000）。

**Comment by sliverloong** [comment]
xml文件
`<cn.iwgang.countdownview.CountdownView
                app:isHideTimeBackground="false"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:isShowMinute="true"
                app:isShowSecond="false"
                app:timeTextSize="@dimen/countdownview_time_ts"
                app:timeTextColor="@android:color/white"
                app:timeBgColor="@color/red_bg2"
                app:suffixDay="@string/suffix_day"
                app:suffixHour="@string/suffix_hour"
                app:suffixMinute="@string/suffix_minute"
                app:suffixTextSize="@dimen/min_txtsize"
                app:suffixTextColor="@color/txt_grey1"
                app:timeBgRadius="2dp" />`

**Comment by iwgang** [comment]
如果是自己控件的倒计时，检查一下有没有倒计时结束后去停止CountdownView，或者调用CountdownView的allShowZero()方法

**Comment by javakam** [comment]
我那个是从联网实体里面拿出来的时间，改了一些东西，过两天我写个demo给你

**Comment by iwgang** [comment]
@javakam  好的，谢谢

**Comment by sliverloong** [comment]
我找到了我的错误，int越界了，不是控件的问题....,当初我只是简单打印了下，int转String不会有越界所以看到是正的
