### ISSUE TITLE
如果手机在RV倒计时的页面后，回到后台调节本地时间会出现时间增加和时间减少的情况

### ISSUE THREAD

**Issue by onemorechoice** [iwgang/CountdownView#15]

**Comment by iwgang** [comment]
列表的使用方式我这边只是给了简单的Demo，没有针对本地时间去做容错优化，这块需要自己判断本地时间改变，然后动态同步倒计时的计数器

由于CountdownView库重点在于UI，所以不会在计时那块做过多的定制判断（判断太多会影响UI绘制效率）
