### ISSUE TITLE
多次调用.start后倒计时不启动

### ISSUE THREAD

**Issue by WillSprint** [iwgang/CountdownView#19]
多次调用start方法，有时候倒计时是停止的

**Comment by iwgang** [comment]
什么场景下会需要多次调用start？
是同个时间还是不同时间

**Comment by WillSprint** [comment]
不同的时间。场景如下：商品销售倒计时页面会有下拉刷新功能，用户多次刷新的话得到的时间是不一样的，逻辑上刷新结束之后应该先停止当前倒计时然后开始新的倒计时

**Comment by iwgang** [comment]
试下先stop再start

**Comment by WillSprint** [comment]
已经尝试过，是无效的。

**Comment by iwgang** [comment]
呃，我测试没有重现出来，可以提供一下对应代码及重现步骤吗？

**Comment by Calamus-Cajan** [comment]
在RecyclerView的item中，重绘后也会出现停止倒计时，adpater用的是BaseRecyclerViewAdapterHelper。
demo里设置太繁琐了。

**Comment by iwgang** [comment]
@Calamus-Cajan rv和lv不可以调用start喔，要自己控制所有时间的倒计时，然后调用updateShow方法来更新显示

**Comment by Calamus-Cajan** [comment]
@iwgang CountdownView控件要和item一一对应存起来吗？

**Comment by iwgang** [comment]
@Calamus-Cajan 具体参照Demo吧，没多复杂，只是把倒计时任务和和CountdownView分离，然后不间隔去刷新CountdownView显示而已

否则如果使用start，创建的倒计时任务在滚动后会被回收，加上重复创建同一个item的倒计时任务，性能受很大影响

**Comment by Calamus-Cajan** [comment]
@iwgang 我参照demo试试

**Comment by xiaokun19931126** [comment]
这个会不会造成内存泄漏啊，比如我一个页面有不少这种倒计时控件，类似那种抢购。感觉非常占内存吧，页面多的话！

**Comment by iwgang** [comment]
@xiaokun19931126 
不会，不同场景下都有提供Demo，如果实在怕泄露，可以自己去做计时器逻辑，把CountdownView只作UI显示组件来使用

**Comment by mrchenmo** [comment]
@Calamus-Cajan 你在BaseRecyclerViewAdapterHelper这里面用的时候有BIG吗？我用的新版分页的时候有bug

**Comment by Calamus-Cajan** [comment]
@mrchenmo BIG?没什么问题，不过逻辑是自己写的，跟作者的不一样。总的来说，包括BaseRecyclerViewAdapterHelper都有坑

**Comment by mrchenmo** [comment]
@Calamus-Cajan 哦哦，我参照作者的逻辑写的然后分页的时候有点BUG还没解决，你的倒计时的逻辑代码可以贴出来参考一下吗？我用的也是BaseRecyclerViewAdapterHelper。

**Comment by Joslyn-Chen** [comment]
@mrchenmo _(:з」∠)_现在才发现。就像作者所说的，重要的是倒计时的逻辑，要么后台帮你计算好了时间，要么自己更新时间，item里CountdownView要一一对应。
