### ISSUE TITLE
请问下：这个符号怎么画出来的？没看到画：啊

### ISSUE THREAD

**Issue by melody1993** [iwgang/CountdownView#23]

**Comment by iwgang** [comment]
![image](https://cloud.githubusercontent.com/assets/3657121/19374290/1187e67c-91fd-11e6-8d2f-2f269adc5014.png)

如果没显示出来，检查一下颜色及 suffix 的字号

**Comment by melody1993** [comment]
我看demo上主页里布局没设置mSuffix为：啊？怎么就显示为为：呢？
