### ISSUE TITLE
How to change text and background color on timer onEnd()

### ISSUE THREAD

**Issue by khalid-mahmood** [iwgang/CountdownView#24]
how i can change the text and background color of countdownview ?

**Comment by iwgang** [comment]
See [customization](https://github.com/iwgang/CountdownView#customization) or  [activity_main.xml](https://github.com/iwgang/CountdownView/blob/master/app/src/main/res/layout/activity_main.xml)

**Comment by khalid-mahmood** [comment]
@iwgang when countdownview  onEnd() Event call then i want to change text and background color RED 
how i can ?

**Comment by iwgang** [comment]
@khalid-mahmood 

try it

```
 CountdownView mCountdownView;
  void onEnd() {
    DynamicConfig.Builder dynamicConfigBuilder = new DynamicConfig.Builder();
    dynamicConfigBuilder.setTimeTextColor(0xFFFFFFFF)
                                        .setSuffixTextColor(0xFF000000)
    mCountdownView.setBackroundColor(0xFF0000);
    mCountdownView..dynamicShow(dynamicConfigBuilder.build());
  }


```

**Comment by khalid-mahmood** [comment]
Thanx... 👍 
Nice Work..
