### ISSUE TITLE
我在RV中使用，数据是分页的。一共有九条数据，前几条都是正常显示的。当滑到第五条的时候，倒计时停止。再往下拉开始分页下面数据有正常。

### ISSUE THREAD

**Issue by mrchenmo** [iwgang/CountdownView#28]
这是为什么

**Comment by iwgang** [comment]
参考下 [Demo](https://github.com/iwgang/CountdownView/blob/master/app/src/main/java/cn/iwgang/countdownviewdemo/RecyclerViewActivity.java)

**Comment by mrchenmo** [comment]
我就是参考的demo，来的然后复用还出现了问题。作者你这个项目有在真是项目中用过吗？demo可以用网络请求的数据写吗？

**Comment by iwgang** [comment]
肯定用过阿！
说白了这就是一个自定义 View，主要就是辅助显示而已
自己跑跑 Demo 看有没问题，自己控制好倒计时怎么可能出现你所说的那些问题
