### ISSUE TITLE
底下这段代码不太懂

### ISSUE THREAD

**Issue by gaohequan** [iwgang/CountdownView#29]
看代码 不写for循环 或者只写mCvCountdownView.updateShow(1);
没有任何影响也会倒计时。
请问这个倒计时逻辑是否是必须的还是试用某种情形。

CountdownView mCvCountdownView = (CountdownView)findViewById(R.id.cv_countdownViewTest1);
mCvCountdownView.start(995550000); // 毫秒

// 或者自己编写倒计时逻辑，然后调用updateShow来更新UI
for (int time=0; time<1000; time++) {
    mCvCountdownView.updateShow(time);
}

**Comment by iwgang** [comment]
```mCvCountdownView.start(xxx)``` 输入倒计时的数值后，内部会启动计时器进行倒计时
```mCvCountdownView.updateShow(xxx)``` 表示倒计时逻辑由自己去控制，然后传值给 `CountdownView` 来作显示

简单说就是上面那个会内部启动定时器，下面那个不会启动定时器，只作为显示，逻辑控制反转给调用者，一般列表（ListView、RecyclerView）用下面那种

**Comment by gaohequan** [comment]
好的，我去看看demo
