### ISSUE TITLE
倒计时控件不能对齐

### ISSUE THREAD

**Issue by a512509050** [iwgang/CountdownView#38]
![oy i ndt 6pyn69a10a17n](https://cloud.githubusercontent.com/assets/18045999/23162545/8584c40a-f869-11e6-845e-5383081287ba.png)
和前面的textview在一个线性布局中，但是无法对齐，textsize都是12sp

**Comment by iwgang** [comment]
数字和文字显示上肯定是不一样大小的，把数字调大点字号吧
