### ISSUE TITLE
跳两秒问题

### ISSUE THREAD

**Issue by adminLiu-s** [iwgang/CountdownView#39]
我项目中就一个textview需要一个倒计时，之前自己用写的转换成天时分秒后也会跳两秒，就是一次性会减掉两秒，我设置的是1秒，后来把你项目中的CustomCountDownTimer拷过来之后还是一样会跳两秒，这个怎么解决？

**Comment by iwgang** [comment]
呃，会吗？  把代码发我看下，系统的CountDownTimer是因为最后一秒会有时候有些慢，我才重新定制了一点它的内容，正常倒计时数字应该是一样的

**Comment by adminLiu-s** [comment]
直接就是用的CountDownTimer，丢进time和间隔时间，然后start，总是跳两秒。。。。

**Comment by iwgang** [comment]
```
        new CountDownTimer(10 * 1000, 1000) {
            @Override
            public void onTick(long millisUntilFinished) {
                Log.i("wg", "CountDownTimer > onTick()：" + (millisUntilFinished / 1000));
            }

            @Override
            public void onFinish() {
                Log.i("wg", "CountDownTimer > onFinish()");
            }
        }.start();
```

![image](https://cloud.githubusercontent.com/assets/3657121/23253353/26e89462-f9ef-11e6-8c50-c1ca53fc6a31.png)


你的不是这样的？  ps：从 8 开始是正常的

**Comment by adminLiu-s** [comment]
是这样写的啊，然后就把毫秒转换成天时分秒，但为毛总是跳两秒搞不懂

![image](https://cloud.githubusercontent.com/assets/11938143/23292736/ca9ecc40-fa9c-11e6-82a3-58327414a8ec.png)

**Comment by iwgang** [comment]
没明白你这个问题和这个库有什么关联？

**Comment by iwgang** [comment]
检查一下算法吧，并且你这个使用场景着实看不懂
