### ISSUE TITLE
DynamicConfig

### ISSUE THREAD

**Issue by xinpengfei520** [iwgang/CountdownView#42]
DynamicConfig constructor is a private access , so I can't get a instance , I want to config DynamicShow , due to countDownView.dynamicShow() method need a DynamicConfig type parameter,can you update DynamicConfig constructor permission modifier is public ?

**Comment by iwgang** [comment]
···
new DynamicConfig.Builder 
···
？

**Comment by xinpengfei520** [comment]
No , new DynamicConfig.

**Comment by iwgang** [comment]
为什么需要 new DynamicConfig？  这个本身是个构造器
