### ISSUE TITLE
recyclerview，或者listview都不能显示时间背景，动态设置时间背景也无效

### ISSUE THREAD

**Issue by yxyaxng** [iwgang/CountdownView#44]

**Comment by iwgang** [comment]
有背景和无背景的不能通过代码来转换，是两种形态，需要用预留的方式来 setVisibility

**Comment by yxyaxng** [comment]
![qq 20170504154439](https://cloud.githubusercontent.com/assets/24906252/25694311/a1acb764-30e0-11e7-9fe0-79c6b653eb32.jpg)
在recyclerview上没有效果，不管在xml配置还是动态，大神，不好意思呀，我真的不懂什么形态

**Comment by yxyaxng** [comment]
DynamicConfig.Builder dynamicConfigBuilder = new DynamicConfig.Builder();
                    DynamicConfig.BackgroundInfo backgroundInfo = new DynamicConfig.BackgroundInfo();
                    backgroundInfo.setColor(0xFF000000)
                            .setSize(40f)
                            .setRadius(3f)
                            .setShowTimeBgDivisionLine(true)
                            .setDivisionLineColor(Color.parseColor("#30FFFFFF"))
                            .setDivisionLineSize(1f);
                    dynamicConfigBuilder.setTimeTextSize(22)
                            .setTimeTextColor(0xFFFFFFFF)
                            .setTimeTextBold(true)
                            .setSuffixTextColor(0xFF000000)
                            .setSuffixTextSize(18)
                            .setSuffixTextBold(true)
                            .setBackgroundInfo(backgroundInfo)
                            .setShowDay(true).setShowHour(true).setShowMinute(true).setShowSecond(true).setShowMillisecond(true);
                    mCvCountdownView.dynamicShow(dynamicConfigBuilder.build());
动态设置跟xml配置时间背景在recyclerview上没有效果，就是没有背景
![image](https://cloud.githubusercontent.com/assets/24906252/25694442/423fc84c-30e1-11e7-995f-42bf4e64f3bf.png)

**Comment by iwgang** [comment]
```
<FrameLayoyt>
   <CountdownView ... app:isHideTimeBackground="true" android:visibility="visible" />
   <CountdownView ... app:isHideTimeBackground="false" android:visibility="gone" />
</FrameLayoyt>
```
