### ISSUE TITLE
RecyclerView页面复用有问题

### ISSUE THREAD

**Issue by zgy1014** [iwgang/CountdownView#48]
1.当我在RecyclerView页面的第一个item有一个定时器的时候（其他item没有），我滑动到下面不可视的状态，定时器会停止走动！！！（当然因为你这边都是有定时器的，所以你这边的demo会出现复用的问题！！）

**Comment by iwgang** [comment]
道理不是一个道理吗，跟其它 item 没定时器有什么区别，不就多加一两个判断而已吗？  自己好好思考下自己的实现是否哪里有问题
