### ISSUE TITLE
有点问题需要请教

### ISSUE THREAD

**Issue by ljackChen001** [iwgang/CountdownView#49]
您好作者，在RecyclerView中使用倒计时的时候，上下滑动  倒计时会暂停 ，多滑动几次就，变成0了,下拉刷新 时间又重置了，怎么解决这个问题啊 ，我Adapter继承的是BaseQuickAdapter com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.15这个里面的BaseAdapter

**Comment by zgy1014** [comment]
我也遇到了同样的问题，下滑动，上面的就停止计时了，解决了停止计时，然后计时到最后结束后又不能重新给值重新计时了！

**Comment by ljackChen001** [comment]
请教下怎么解决的停止计时？

**Comment by zgy1014** [comment]
你要用服务器给的时间减去系统的时间，在去给值到定时器，和demo一样

**Comment by ljackChen001** [comment]
服务器返回的就是秒数  我是用的当前时间加  服务器返回时间*1000
public class RentOrderAdapter extends BaseQuickAdapter<LeaseOrder, BaseViewHolder> {
    List<LeaseOrder> data;
    private CountdownView tvTime;

    public RentOrderAdapter(int layoutResId, @Nullable List<LeaseOrder> data) {
        super(layoutResId, data);
        this.data = data;
    }

    @Override
    protected void convert(BaseViewHolder holder, LeaseOrder leaseOrder) {
        long curTime = System.currentTimeMillis();
        leaseOrder.setEndTime(curTime + (60 * 1000));
        LogUtils.d(leaseOrder.getEndTime());
        //        CountDownTimer countDownTimer;
        holder.setText(R.id.tv_num, leaseOrder.getOrderId())
                .setText(R.id.tv_getcartime, TimeUtils.getYearMonthHH(leaseOrder.getOrderGetTime()))
                .setText(R.id.tv_getcararea, leaseOrder.getOrderGetAddress())
                .setText(R.id.tv_orderallprice, "￥" + leaseOrder.getOrderFee());
        tvTime = holder.getView(R.id.tv_time);
        //        if (leaseOrder.getOrderStateCode().getCodeValue().equals("0")) {
        tvTime.setVisibility(View.VISIBLE);
        refreshTime(leaseOrder.getEndTime()-System.currentTimeMillis());
//        tvTime.setPrefixRuntext("当前订单还剩");
        //            mTvTime.setSuffixRuntext("付款，未付款将被取消！");
        //            mTvTime.setTotaltime(Integer.parseInt(leaseOrder.getPayOver()));
        //            mTvTime.isAllowRun(true);
        //            holder.setText(R.id.tv_time, leaseOrder.getPayOver());
        //        }
        if (leaseOrder.getOrderStateCode() != null) {
            holder.setText(R.id.tv_state, leaseOrder.getOrderStateCode().getCodeName() + "");
        }
        if (leaseOrder.getVehicleNoLeftCode() != null && leaseOrder.getVehicleNoContentCode() != null) {
            holder.setText(R.id.tv_carstate, leaseOrder.getVehicleNoLeftCode().getCodeName() + leaseOrder
                    .getVehicleNoContentCode().getCodeName() + leaseOrder.getVehicleNoRight());
        }
    }

    public void refreshTime(long leftTime) {
        if (leftTime > 0) {
            tvTime.start(leftTime);
        } else {
            tvTime.stop();
            tvTime.allShowZero();
        }
    }

    /**
     * 以下两个接口代替 activity.onStart() 和 activity.onStop(), 控制 timer 的开关
     */
//    @Override
//    public void onViewAttachedToWindow(BaseViewHolder holder) {
//        int pos = holder.getLayoutPosition();
//        LeaseOrder itemInfo = data.get(pos);
//        refreshTime(itemInfo.getEndTime() - System.currentTimeMillis());
//    }
//
//    @Override
//    public void onViewDetachedFromWindow(BaseViewHolder holder) {
//        tvTime.stop();
//    }
}

**Comment by ljackChen001** [comment]
服务器返回的就是秒数  我是用的当前时间加  服务器返回时间*1000
public class RentOrderAdapter extends BaseQuickAdapter<LeaseOrder, BaseViewHolder> {
    List<LeaseOrder> data;
    private CountdownView tvTime;

    public RentOrderAdapter(int layoutResId, @Nullable List<LeaseOrder> data) {
        super(layoutResId, data);
        this.data = data;
    }

    @Override
    protected void convert(BaseViewHolder holder, LeaseOrder leaseOrder) {
        long curTime = System.currentTimeMillis();
        leaseOrder.setEndTime(curTime + (60 * 1000));
        LogUtils.d(leaseOrder.getEndTime());
        //        CountDownTimer countDownTimer;
        holder.setText(R.id.tv_num, leaseOrder.getOrderId())
                .setText(R.id.tv_getcartime, TimeUtils.getYearMonthHH(leaseOrder.getOrderGetTime()))
                .setText(R.id.tv_getcararea, leaseOrder.getOrderGetAddress())
                .setText(R.id.tv_orderallprice, "￥" + leaseOrder.getOrderFee());
        tvTime = holder.getView(R.id.tv_time);
        //        if (leaseOrder.getOrderStateCode().getCodeValue().equals("0")) {
        tvTime.setVisibility(View.VISIBLE);
        refreshTime(leaseOrder.getEndTime()-System.currentTimeMillis());
//        tvTime.setPrefixRuntext("当前订单还剩");
        //            mTvTime.setSuffixRuntext("付款，未付款将被取消！");
        //            mTvTime.setTotaltime(Integer.parseInt(leaseOrder.getPayOver()));
        //            mTvTime.isAllowRun(true);
        //            holder.setText(R.id.tv_time, leaseOrder.getPayOver());
        //        }
        if (leaseOrder.getOrderStateCode() != null) {
            holder.setText(R.id.tv_state, leaseOrder.getOrderStateCode().getCodeName() + "");
        }
        if (leaseOrder.getVehicleNoLeftCode() != null && leaseOrder.getVehicleNoContentCode() != null) {
            holder.setText(R.id.tv_carstate, leaseOrder.getVehicleNoLeftCode().getCodeName() + leaseOrder
                    .getVehicleNoContentCode().getCodeName() + leaseOrder.getVehicleNoRight());
        }
    }

    public void refreshTime(long leftTime) {
        if (leftTime > 0) {
            tvTime.start(leftTime);
        } else {
            tvTime.stop();
            tvTime.allShowZero();
        }
    }

    /**
     * 以下两个接口代替 activity.onStart() 和 activity.onStop(), 控制 timer 的开关
     */
//    @Override
//    public void onViewAttachedToWindow(BaseViewHolder holder) {
//        int pos = holder.getLayoutPosition();
//        LeaseOrder itemInfo = data.get(pos);
//        refreshTime(itemInfo.getEndTime() - System.currentTimeMillis());
//    }
//
//    @Override
//    public void onViewDetachedFromWindow(BaseViewHolder holder) {
//        tvTime.stop();
//    }
}
这是我的adapter

**Comment by zgy1014** [comment]
715603774我的qq

**Comment by iwgang** [comment]
需要自己维护好倒计时，CountdownView 在列表中只当作 自定义 View 使用而已，计时逻辑独立开，这样灵活性也更大

具体参考 Demo
