### ISSUE TITLE
Not show zero when countdown number is small than 10

### ISSUE THREAD

**Issue by Piasy** [iwgang/CountdownView#5]
i.e. `9` rather than `09`.

**Comment by iwgang** [comment]
倒计时貌似普遍都是2位吧，10以下用0x

**Comment by Piasy** [comment]
如果只有秒数倒计时，显示`09`好，还是`9`好？也许见仁见智，能否可配置？

**Comment by iwgang** [comment]
嗯，如果只显示秒数的时候，那个确实显示9好，我优化一下代码
感谢

**Comment by iwgang** [comment]
不好意思，刚重新又看了遍代码，由于当初设计这个库时没有事先考虑过这种情况，改这个需要牵动很多判断及测量

所以 “只显示秒钟并且不想在<10的数值前面加0” 的场景下不建议使用此库

**Comment by Piasy** [comment]
@iwgang 没关系哈，还是好赞的！
