### ISSUE TITLE
RecyclerView的问题

### ISSUE THREAD

**Issue by zgy1014** [iwgang/CountdownView#50]
如果我设置了RecyclerView的第一个item有个定时器，当我下滑到第二页的时候，第一个item的定时器时间结束了不会调用setOnCountdownEndListener方法么 ？？

**Comment by iwgang** [comment]
被回收了，肯定不会再回调了，但可以自己维护好各 item 的倒计时，在倒计时结束后也自然而然知道哪个已经 end 了
