### ISSUE TITLE
How to use Interval

### ISSUE THREAD

**Issue by bahramnooraii** [iwgang/CountdownView#53]
Hi, thanks for your great library.
I want show some time in my application and i want when lasted 5s show me toast.
For example : I want how 17s countTimer, when this timer receive to 5s show me toast "just 5s".

how can i it? please help me

**Comment by bahramnooraii** [comment]
I use this code, but show me ever 5s .

```
        long time1 = (long) 17 * 1000;
        mCvCountdownViewTest1.start(time1);
mCvCountdownViewTest1.setOnCountdownIntervalListener(5000, new CountdownView.OnCountdownIntervalListener() {
            @Override
            public void onInterval(CountdownView cv, long remainTime) {
                Toast.makeText(MainActivity.this, "Just 5s ", Toast.LENGTH_SHORT).show();
            }
        });
```

I want just lasted 5s not ever 5s.

how can i it?

**Comment by bahramnooraii** [comment]
can you help me my friend? i need this. please help me

**Comment by alex2390** [comment]
Can I modify the color of the font in the code?

**Comment by iwgang** [comment]
Judge in onInterval
