### ISSUE TITLE
请问为什么我隐藏不了分钟的00呢？

### ISSUE THREAD

**Issue by Clearlee** [iwgang/CountdownView#54]
我只想显示00天00时，隐藏00分，设置如下
![t 5 h jyw5 6p qyahoc](https://user-images.githubusercontent.com/10986957/27064710-4d41095e-502b-11e7-9e15-d9946070cc46.png)

但是始终无法隐藏分钟00，请问该怎么解决呢？
![qq 20170613112624](https://user-images.githubusercontent.com/10986957/27064713-5057040e-502b-11e7-9279-b505ca783c68.png)

**Comment by iwgang** [comment]
确实有这个问题，但最后那个其实是秒钟，不是分钟，目前 bug 是如果秒钟和分钟都隐藏了，会显示秒钟
近期会修复此问题，谢谢反馈

如果急需使用，可以暂时使用下面方法在进行重新设置
```
                DynamicConfig.Builder dynamicConfigBuilder = new DynamicConfig.Builder();
                dynamicConfigBuilder.setShowDay(true);
                dynamicConfigBuilder.setShowHour(true);
                dynamicConfigBuilder.setShowMinute(false);
                dynamicConfigBuilder.setShowSecond(false);
                dynamicConfigBuilder.setShowMillisecond(false);
                mCvCountdownViewTest1.dynamicShow(dynamicConfigBuilder.build());
```

**Comment by iwgang** [comment]
use 
```
compile 'com.github.iwgang:countdownview:2.1.5'
```
