### ISSUE TITLE
recyclerview 嵌套一个recyclerview，嵌套的recyclerviewl 里面的定时器不更新

### ISSUE THREAD

**Issue by yxyaxng** [iwgang/CountdownView#55]
嵌套的recyclerview适配器已经跟作者适配器维护时间一样的方法

**Comment by LIUPING789** [comment]
我是到的问题是   recyclerview  添加 footerView (注：时间是添加foooterview)  时间不能刷新。   有朋友遇到的吗

**Comment by AlvinQiang** [comment]
@KnightOneAdmin 我也有类似问题，请问如何解决的

**Comment by kpioneer123** [comment]
我也遇到了，请问楼上解决了吗?

**Comment by iwgang** [comment]
#74
