### ISSUE TITLE
依赖2.1.5版本后，AS中布局预览失败

### ISSUE THREAD

**Issue by a512509050** [iwgang/CountdownView#59]
![image](https://user-images.githubusercontent.com/18045999/27768674-aa50718c-5f4b-11e7-85ca-19788a4ba3ae.png)
将依赖去掉又可以预览了
这是我的编译版本
```
compileSdkVersion: 25,
buildToolsVersion: "25.0.3",
minSdkVersion    : 15,
targetSdkVersion : 25,
```
我不知道是不是库的版本21低了的原因

**Comment by a512509050** [comment]
感觉确实是build版本的原因，我把库的代码拷贝到项目组，也可以预览布局了

**Comment by iwgang** [comment]
好的，谢谢，到时这边调试一下

主要平时极少会看预览，所以没太留意这个

**Comment by wl386123298** [comment]
我还以为这个问题换了As了，折腾很久了！

**Comment by wl386123298** [comment]
建议跟下下build版本，21太低了！！！

**Comment by KnightOneAdmin** [comment]
这个问题解决了吗？   我用xxxxx:latest.release 还是有这个预览失败的这个问题

**Comment by iwgang** [comment]
Use：```compile 'com.github.iwgang:countdownview:2.1.6'```

**Comment by macouen** [comment]
我折腾了两天，把近两天的所有提交一个个排查，最后发现countdownview的问题。
