### ISSUE TITLE
About Handler 

### ISSUE THREAD

**Issue by NicodeLee** [iwgang/CountdownView#6]
Since this Handler is declared as an inner class, it may prevent the outer class from being garbage collected. If the Handler is using a Looper or MessageQueue for a thread other than the main thread, then there is no issue. If the Handler is using the Looper or MessageQueue of the main thread, you need to fix your Handler declaration, as follows: Declare the Handler as a static class; In the outer class, instantiate a WeakReference to the outer class and pass this object to your Handler when you instantiate the Handler; Make all references to members of the outer class using the WeakReference object.

**Comment by iwgang** [comment]
Handler？ 库里面没有使用Handler，方便说明下是哪块吗？

**Comment by NicodeLee** [comment]
@iwgang https://github.com/iwgang/CountdownView/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcn%2Fiwgang%2Fcountdownview%2FCustomCountDownTimer.java

**Comment by iwgang** [comment]
喔，是这个倒计时类，这个是完全copy的android.os.CountDownTimer源码，只做了细小调整
现在有出现因此引起的内存泄露吗？

**Comment by NicodeLee** [comment]
我在项目中测试下看效果，放在Recyclerview中，不知道会不会有问题。有问题再提反馈

**Comment by iwgang** [comment]
嗯，好的，谢谢你的反馈，其实这个我有测试过，只要在不需要时处理好回收工作(非列表使用时可以不用关注回收)，是不会出现泄露问题的。

不过在RecyclerView和ListView中使用时，不建议直接调用CountdownView的start()方法来使用

可以用一个集合去给维护一个CustomCountDownTimer处理倒计时工作，然后使用CountdownView的updateShow()方法更新显示
