### ISSUE TITLE
使用timeBg的时候天数不能转换成小时

### ISSUE THREAD

**Issue by moyergo** [iwgang/CountdownView#60]
isConvertDaysToHours="true"
isHideTimeBackground="false"
isShowDay="false"
这样设置的话，天数不能转换成小时，看了源码，在BackgroundCountdown类里并没有相关处理。

**Comment by moyergo** [comment]
if (ta.getBoolean(R.styleable.CountdownView_isHideTimeBackground, true)) {
            isConvertDaysToHours = ta.getBoolean(R.styleable.CountdownView_isConvertDaysToHours, false);
 }
请教下为什么如果隐藏背景就转换天数成小时呢？是背景不好处理么？

**Comment by iwgang** [comment]
背景模式的改动太多，前期没有考虑进去，主要是时间背景绘制动态，建议自己 clone 出去，根据自己需求定制
