### ISSUE TITLE
suffixGravity:center is invalid

### ISSUE THREAD

**Issue by Raysy** [iwgang/CountdownView#61]
安装demo的时候打开的应用：都是在top的位置的，但是xml的设置是center；在AS上预览是在居中的位置，但是安装在手机上就变成跟top的位置差不多 了

**Comment by xlp-shawn** [comment]
center属性无效的问题解决了吗  我也遇到center属性无效的情况

**Comment by iwgang** [comment]
给下布局，调整下字号，如果和时间字号一样，会有空白区，其实已经剧中的，但犹豫字体空白区，导致看上去不是剧中

**Comment by xlp-shawn** [comment]
<cn.iwgang.countdownview.CountdownView
        android:id="@+id/goods_details_flash_sale_imm_count"
        android:layout_width="wrap_content"
        android:layout_height="@dimen/x36"
        app:isHideTimeBackground="false"
        app:isShowDay="true"
        app:isShowHour="true"
        app:isShowMillisecond="false"
        app:isShowMinute="true"
        app:isShowSecond="true"
        app:suffixDay="天"
        app:suffixHour="时"
        app:suffixMinute="分"
        app:suffixSecond="秒"
        app:suffixGravity="center"
        app:suffixTextColor="@color/bm_color_e85b8a"
        app:suffixTextSize="@dimen/x22"
        app:timeBgColor="@color/bm_color_333333"
        app:timeTextColor="@color/bm_color_ffffff"
        app:timeTextSize="@dimen/x22"
        app:timeBgRadius="@dimen/x4"
        app:timeBgBorderRadius="@dimen/x4"
        />
![image](https://user-images.githubusercontent.com/21071322/32261784-d77b826c-bf0b-11e7-9c98-ba30a4aa7583.png)

**Comment by iwgang** [comment]
应该是 suffix 设置字号过大问题，检查下布局
