### ISSUE TITLE
为什么天数转成小时要依赖于实现隐藏控件背景？

### ISSUE THREAD

**Issue by Love667767** [iwgang/CountdownView#62]
class CountdownView extends View {

        public CountdownView(Context context, AttributeSet attrs, int defStyleAttr) {
		super(context, attrs, defStyleAttr);
		TypedArray ta = context.obtainStyledAttributes(attrs, R.styleable.CountdownView);
		isHideTimeBackground = ta.getBoolean(R.styleable.CountdownView_isHideTimeBackground, true);
		mCountdown = isHideTimeBackground ? new BaseCountdown() : new BackgroundCountdown();
		// 初始化属性
		mCountdown.initStyleAttr(context,ta);
		ta.recycle();
		mCountdown.initialize();
        }
    }

    class BaseCountdown {

        public void initStyleAttr(Context context, TypedArray ta) {
		...省略若干代码...
		// 为什么天数转成小时要依赖于实现隐藏控件背景？
		if (ta.getBoolean(R.styleable.CountdownView_isHideTimeBackground, true)) {
			isConvertDaysToHours = ta.getBoolean(R.styleable.CountdownView_isConvertDaysToHours, false);
		}
        }
    }

**Comment by iwgang** [comment]
背景模式不支持 isConvertDaysToHours

**Comment by Love667767** [comment]
如果要显示  会有隐藏的问题吗？

**Comment by iwgang** [comment]
那块没做处理，背景下的时间格子要动态做绘制
有兴趣可以自己 fork 定制化一下，目前项目加不了这么多逻辑，并且这种场景的需求我几乎没见过
