### ISSUE TITLE
您好，倒计时不能刷新的问题。

### ISSUE THREAD

**Issue by gaohequan** [iwgang/CountdownView#63]
NestedScrollView内部嵌套RecyclerView（横行的Linear），当recyclerView中的倒计时item滑动出屏幕再回来的时候倒计时不会倒数刷新。

**Comment by iwgang** [comment]
有没看 Demo ，倒计时有没自己维护好？

**Comment by gaohequan** [comment]
您的demo里通过onViewAttachedToWindow，onViewAttachedToWindow这两个方法维护的倒计时。我们当前时间是取得后台服务器时间并不是手机时间。我再试试该怎么维护，谢谢。
