### ISSUE TITLE
遇到线上异常，求助

### ISSUE THREAD

**Issue by zhangxy1219** [iwgang/CountdownView#68]
首先感谢作者贡献这个倒计时控件！
我们的app使用的还是1.2版本，最近在线上环境收到这样的异常信息
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.graphics.RectF.centerX()' on a null object referenceat ***.CountdownView.onDraw(SourceFile:877)at android.view.View.draw(View.java:17286)at android.view.View.updateDisplayListIfDirty(View.java:16268)at android.view.View.draw(View.java:17052)at android.view.ViewGroup.drawChild(ViewGroup.java:3727)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)at android.view.View.draw(View.java:17289)at android.view.View.updateDisplayListIfDirty(View.java:16268)at android.view.View.draw(View.java:17052)at android.view.ViewGroup.drawChild(ViewGroup.java:3727)at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)at android.view.View.draw(View.java:17289)at android.view.View.updateDisplayListIfDirty(View.java:16268)at android.view.View.draw(View.java:17052)at android.view.ViewGroup.drawChild(ViewGroup.java:3727)at android.view.ViewGroup.dispatchDraw(ViewGroup.java

layout里面的countdownView没有设置isShowDay，看起来是在onMeasure的时候没有初始化mDayBgRectF但在onDraw的时候又试图使用这个变量。
请帮忙看看这个问题，谢谢大家。 @iwgang

**Comment by iwgang** [comment]
方便贴下具体布局么，最好能告之重现流程，感谢

**Comment by swnnn** [comment]
我也遇到了一个类似的问题，在使用BackgroundCountDown时报java.lang.NullPointerException: Attempt to read from field 'float android.graphics.RectF.left' on a null object reference，请问是怎么解决的呢?

布局如下：
<xxx.countdownview.CountdownView
                android:id="@+id/hc_recommend_countdown"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical"
                android:layout_marginRight="10dp"
                app:isHideTimeBackground="false"
                app:isShowDay="false"
                app:isShowHour="true"
                app:isShowMillisecond="false"
                app:isShowMinute="true"
                app:isShowSecond="true"
                app:isShowTimeBgDivisionLine="false"
                app:suffix=":"
                app:suffixHourRightMargin="2dp"
                app:suffixMinuteRightMargin="2dp"
                app:isTimeTextBold="true"
                app:isSuffixTextBold="true"
                app:suffixLRMargin="1dp"
                app:suffixGravity="center"
                app:suffixTextColor="#ffa14d"
                app:suffixTextSize="14sp"
                app:timeBgColor="#FFa14d"
                app:timeTextColor="#FFFFFF"
                app:timeBgSize="20dp"
                app:timeBgRadius="4dp"
                app:timeTextSize="14sp" />
