### ISSUE TITLE
在listview里可以用吗

### ISSUE THREAD

**Issue by Cornflower1991** [iwgang/CountdownView#7]
在listview里可以用吗

**Comment by Cornflower1991** [comment]
在listview里 多这个对象 滑动不会卡顿吗

**Comment by iwgang** [comment]
@Cornflower1991 可以用，不过不建议直接调用CountdownView的start()方法来使用

可以用一个集合去给维护一个CustomCountDownTimer处理倒计时工作，然后使用CountdownView的updateShow()方法更新显示
