### ISSUE TITLE
recyclerview 滑动时，countdownview 数据混乱；

### ISSUE THREAD

**Issue by xiaoxiaohua333** [iwgang/CountdownView#71]
在recyclerview里面使用了countdownview，上下滑动的时候，倒计时混乱。应该是recyclerview数据回收造成的，看到demo里面是使用正常的，不知是如何解决的？

**Comment by iwgang** [comment]
参考 Demo 代码，自己控制并维护好倒计时逻辑

**Comment by xiaoxiaohua333** [comment]
谢谢，之前没有看到源码，已经解决了~

**Comment by yonglf** [comment]
@xiaoxiaohua333 请问你怎么解决的啊
