### ISSUE TITLE
START无法显示出来时间

### ISSUE THREAD

**Issue by xicong** [iwgang/CountdownView#72]
start设置正确的时间，然后并没有显示出来时间
![image](https://user-images.githubusercontent.com/11675597/29448344-cc1d9194-8428-11e7-96d2-47a513a8b251.png)

**Comment by iwgang** [comment]
能否把具体代码及布局贴出来，再深度跑下 Demo 并修改尝试一下

**Comment by xicong** [comment]
![default](https://user-images.githubusercontent.com/11675597/29454135-a192779e-843e-11e7-83d9-be67bf51cd2d.png)
![default](https://user-images.githubusercontent.com/11675597/29454166-bc72712c-843e-11e7-8a40-9ef29ede70fd.png)
不知道为什么，那个start方法不知道怎么回事，直接都不显示，后来发现updateShow可以显示，所以先这样了，等我空余了再结合源码看看

**Comment by iwgang** [comment]
`start(写死一个时间试试)`，比如  `start(24 * 60 * 60 * 1000)`

**Comment by zhangxu2814** [comment]
这个问题我也发现了，一个Activity 多退出 进入几次就会出现这个问题
放在headView 里偶发性这种问题
