### ISSUE TITLE
recycleview 滚动后倒计时就停了，放在viewpager 切换后 也会停止

### ISSUE THREAD

**Issue by silence-jianghuan** [iwgang/CountdownView#73]
求解决办法

**Comment by iwgang** [comment]
view 被移除了肯定停止了，自己维护好倒计时逻辑 ，在列表及所有涉及会被回收的场景下，不能直接调用```start```方法，只建使用```updateShow```

**Comment by LinSir-888** [comment]
@silence-jianghuan recycleview 滚动后倒计时我也遇到了问题，你解决了吗，你是怎么解决的？

**Comment by silence-jianghuan** [comment]
@CoKoOne  updateShow显示时间，然后开子线程 自己倒计时

**Comment by LinSir-888** [comment]
@silence-jianghuan 不明白，能说清楚些吗，或者给一些示例代码？我现在用BaseRecyclerViewAdapterHelper做的RecyclerView适配器，新手，不知道怎么维护啊，感激不尽
