### ISSUE TITLE
 recyclerview  添加 footerView (注：时间是添加foooterview)  时间不能刷新

### ISSUE THREAD

**Issue by LIUPING789** [iwgang/CountdownView#74]
我遇到的问题是   recyclerview  添加 footerView (注：时间是添加foooterview)  时间不能刷新。   有朋友遇到的吗

**Comment by yxyaxng** [comment]
我已经解决了这个问题，你在主适配器里配置footView的时间数据就会刷新

**Comment by Mexicande** [comment]
@yxyaxng 麻烦能多给点提示吗？贴下代码，我也遇到这个问题了！

**Comment by kpioneer123** [comment]
我也遇到了，有解决办法吗？

**Comment by iwgang** [comment]
列表都需要自己维护好倒计时，调用`updateShow`来刷新时间，header 、footer、item 都是一样，在不可见时就会被回收，是不应该直接用 `start` 方法的
