### ISSUE TITLE
如果设置了isHideTimeBackground="false" 无法使用isConvertDaysToHours将多余的天转成成小时

### ISSUE THREAD

**Issue by CMzhizhe** [iwgang/CountdownView#75]
如果我是用了isHideTimeBackground="false" ，当你设置isConvertDaysToHours = true的时候，他是不会将多余的天转换成小时
控件版本:2.1.6

**Comment by iwgang** [comment]
背景模式不支持此属性，这块涉及到背景动态变化，如果有需要可以 clone 下来定制一下这块功能
