### ISSUE TITLE
时间超过24小时

### ISSUE THREAD

**Issue by LayneCui** [iwgang/CountdownView#76]
大神您好，时间超过24小时，只以小时为最大单位可以支持吗？

**Comment by iwgang** [comment]
试试`isConvertDaysToHours`

**Comment by LayneCui** [comment]
试过了，不行。

<cn.iwgang.countdownview.CountdownView
                    android:id="@+id/cv_configurable_time"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="8dp"
                    android:layout_marginRight="8dp"
                    android:padding="5dp"
                    app:isHideTimeBackground="false"
                    app:isShowDay="false"
                    app:isConvertDaysToHours="true"
                    app:isShowHour="true"
                    app:isShowMillisecond="false"
                    app:isShowMinute="true"
                    app:isShowSecond="true"
                    app:suffixGravity="center"
                    app:suffixTextColor="#000000"
                    app:suffixTextSize="13sp"
                    app:timeBgDivisionLineSize="1dp"
                    app:timeBgRadius="3dp"
                    app:timeBgSize="16dp"
                    app:timeTextColor="#FFFFFF"
                    app:timeTextSize="12sp"  />

**Comment by jovikao** [comment]
我遇到一樣的問題，xml 方式不行
但透過程式碼的方式可以 DynamicConfig.Builder().setConvertDaysToHours(true).setShowDay(false) 
@iwgang 是因為程式碼  countdown.dynamicShow(config) 會 override 掉 xml 嗎？

**Comment by iwgang** [comment]
`app:isHideTimeBackground="false"` 只有非背景模式才可以使用 `isConvertDaysToHours`

**Comment by LayneCui** [comment]
试了，的确不行
app:isHideTimeBackground="false"
app:isShowDay="false"
app:isConvertDaysToHours="true"
app:isShowHour="true"

**Comment by iwgang** [comment]
`="true"` 时有效阿，不支持背景模式，上面不是有说吗
