### ISSUE TITLE
isHideTimeBackground=true有个小bug

### ISSUE THREAD

**Issue by she1014** [iwgang/CountdownView#8]
![bug1](https://cloud.githubusercontent.com/assets/16135688/15625868/e85480f2-24e8-11e6-8b76-46efb8af617e.png)

app:isHideTimeBackground="false"
app:isShowSecond="false"
两个同时设置false时会报错

**Comment by iwgang** [comment]
谢谢反馈，这个问题到时有新版本更新时一并列入解决

目前应该不会影响使用吧？，显示背景的场景下秒杀不应该也隐藏才对，不然那几个框框半天都不动有些奇怪

**Comment by she1014** [comment]
谢谢回复，暂不影响
