### ISSUE TITLE
为什么和转换的时间差了2天

### ISSUE THREAD

**Issue by SunJaAc** [iwgang/CountdownView#83]
![qq 20171011155416](https://user-images.githubusercontent.com/19640883/31428172-7cd7b044-ae9c-11e7-96e7-cd0aeea37360.png)
![_20171011155521](https://user-images.githubusercontent.com/19640883/31428201-9fd3e5ae-ae9c-11e7-8a0a-846f7488b5f5.jpg)
转换的是离今天15天，项目中是离今天17天，搞不懂，求解。

**Comment by SunJaAc** [comment]
已解决

**Comment by liguangze** [comment]
@SunJaAc   怎么解决的，我这里也是时间不对应呢，跟时间戳
