### ISSUE TITLE
动态显示隐藏天、时、分

### ISSUE THREAD

**Issue by maxiaoping** [iwgang/CountdownView#85]
customTimeShow(false,false,true,true,false)；此方法已过时，但是想要动态显示隐藏天、时、分应该用什么方法呢？而且这个过时的方法有问题

**Comment by iwgang** [comment]
```dynamicShow```

**Comment by maxiaoping** [comment]
怎么用的呢？给个案例可以吗？例如我想让现实3天3时3分8秒然后到后面的3分8秒，把天和时隐藏掉，这个怎么设置，你这个方法我看了，也没法设置参数呀

**Comment by tangyaogang** [comment]
解决了吗    能动态隐藏掉吗
