### ISSUE TITLE
在不显示天数时，能把天数的时间换算成小时来显示吗？

### ISSUE THREAD

**Issue by zhuzhushang** [iwgang/CountdownView#86]
遇到这样的需求，不显示天数，但是当时间超过24小时时，默认天数时间没有加到小时上面去.
比如还有25小时结束，效果却显示还有1小时结束...

有木有方法修改？

**Comment by iwgang** [comment]
```isConvertDaysToHours```

**Comment by zhuzhushang** [comment]
谢谢。看了下源码，我也发发现了。
