### ISSUE TITLE
关于第二次stop()以后再次start()的bug

### ISSUE THREAD

**Issue by profileCaren** [iwgang/CountdownView#9]
假设已经为mCvCountdownView设置了OnCountdownIntervalListener的间隔时间监听器。mCvCountdownView在调用stop()以后，再次调用start()方法启动的话，很可能不会回调onInterval()方法，因为对象的成员变量mPreviouIntervalCallbackTime在stop()以后并没有被置零。解决办法是在stop()以后将之置零；或者增加一个set方法，在再次start之前置零。
另外这个倒计时很好用，谢谢！

**Comment by iwgang** [comment]
谢谢反馈，近期会有个重构版本发出，届时也会把现有bug都修复

**Comment by profileCaren** [comment]
期待
