### ISSUE TITLE
Is any way to show only minutes and seconds

### ISSUE THREAD

**Issue by melody-pps** [iwgang/CountdownView#93]
When i try to start count down more than 1 hours and set isShowHour = false (eg. 90 minutes)

The count down view start as 30:00, if set isShowHour = true it's look work properly (count down will show as 01:30:00)

Is any way or work around to start count down as 90:00 ?

**Comment by leah-pgdn** [comment]
Can replicate this issue also

**Comment by iwgang** [comment]
``` xml
isShowDay="false"
isShowHour="false"
isShowMinute="true"
isShowSecond="true"
isShowMillisecond="false"
```
