### ISSUE TITLE
无法自动隐藏。

### ISSUE THREAD

**Issue by tangyaogang** [iwgang/CountdownView#98]
isShowDay(true) isShowHour(true) ，没有作用、。

**Comment by iwgang** [comment]
请给出完整代码，谢谢

**Comment by KentFeng** [comment]
大哥，天和小时能自动显示和隐藏，要隐藏分，怎么设置 @iwgang

**Comment by iwgang** [comment]
@KentFeng 自动显示只支持天和小时，动态设置分意义不大，如果有特定的需求可以 clone 代码参照天、小时的方式定制
